spring:
  main:
    banner-mode: off
  liquibase:
    change-log: db/changelog.xml
  datasource:
    url: jdbc:h2:.\test-orders
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
    show-sql: true
management:
  endpoints:
    access:
      default: unrestricted
server:
  port: 8081