FROM test-project-deps:dep AS build

WORKDIR /app

COPY pom.xml .
COPY api-contracts api-contracts
COPY PaymentApi PaymentApi
COPY UserApi/pom.xml UserApi/pom.xml

RUN mvn package -pl org.arcsoft:payment-api,org.arcsoft:api-contracts

FROM eclipse-temurin:25_36-jre-jammy
WORKDIR /app
COPY --from=build /app/PaymentApi/target/payment-api-1.0-SNAPSHOT.jar app.jar
COPY test-orders.mv.db .
COPY test-orders.trace.db .

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "app.jar"]